{
  # robot configurations, 0->right 1->left
  # comment out robot #1 if only using 1 arm
  "robots": [
    {
      "robot_type": "ur5e",
      "robot_ip": "127.0.0.1",
      "robot_obs_latency": 0.06, "robot_action_latency": 0.3, "tcp_offset": 0.235,

      # table height for finger-table collision avoidance
      # -inf to disable
      "height_threshold": 0.017,

      # sphere collision primitive size and location for inter-gripper collision avoidance
      # 0 to disable
      "sphere_radius": 0.13, "sphere_center": [0, 0, -0.185]
    },
  ],

  # gripper configurations, 0->right 1->left
  "grippers": [
    {
      "robot_type": "dh",
      "gripper_ip": "127.0.0.1",
      "gripper_port": "/dev/ttyUSBDH_", "gripper_obs_latency": 0.01, "gripper_action_latency": 0.01,
      "max_width": 0.08,
      "min_width": 0.0,
      "grasp_threshold": 0.055,
      "grasp_offset": 0.01
    },
  ],

  "vacuums": [
      {
          "gripper_ip": "127.0.0.1",
          "max_width": 0.08,
          "min_width": 0.0,
          "grasp_threshold": 0.055,
          "grasp_offset": 0.01
      },
  ],

  # cameras settings
  "cameras": [
    {
      "serial_number": 'camera_0',
      "height": 1280,
      "width": 720,
      "fps": 30,
      "address": "tcp://localhost:5566"
    },
    {
      "serial_number": 'camera_1',
      "height": 1280,
      "width": 720,
      "fps": 30,
      "address": "tcp://localhost:5567"
    },
  ],

  # transformation right arm's base frame in left arm's base coordinate frame
  "tx_left_right": [
    [ 0.99996206,  0.00661996,  0.00566226, -0.01676012],
    [-0.00663261,  0.99997554,  0.0022186 , -0.60552492],
    [-0.00564743, -0.00225607,  0.99998151, -0.007277  ],
    [ 0.        ,  0.        ,  0.        ,  1.        ]
  ]
}